name: Build Android

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: "Type de build: APK ou AAB"
        required: true
        default: "APK"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Cloner le repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Installer Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Installer les dépendances du projet
      - name: Install dependencies
        run: npm install

      # 4️⃣ Installer EAS CLI (obligatoire)
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # 5️⃣ Login Expo avec le token
      - name: Expo Login
        run: eas login --token ${{ secrets.EXPO_TOKEN }}

      # 6️⃣ Lancer le build
      - name: Start EAS Build
        run: |
          if [ "${{ github.event.inputs.build_type }}" = "APK" ]; then
            eas build --platform android --profile preview --non-interactive
          else
            eas build --platform android --profile production --non-interactive
          fi

      # 7️⃣ Récupérer l’URL du build
      - name: Get Build URL
        run: eas build:list --limit 1

